root: ../../data
dataset: AmazonBeauty_550_Chron
maxlen: 50
num_heads: 4
num_blocks: 2
hidden_size: 64
dropout_rate: 0.2
mask_prob: 0.5
epochs: 500
batch_size: 256
optimizer: adam
beta1: 0.9
beta2: 0.95
lr: 5.e-4
weight_decay: 1.e-4