root: ../../data
dataset: Amazon2014Beauty_550_LOU

maxlen: 50
num_heads: 1
num_blocks: 2
embedding_dim: 64
dropout_rate: 0.4

epochs: 300
batch_size: 512
optimizer: adam
lr: 5.e-4
weight_decay: 1.e-8

monitors: [LOSS, HitRate@1, HitRate@5, HitRate@10, NDCG@5, NDCG@10]
which4best: NDCG@10