dataset: Yelp2018_10104811_ROU
root: ../../data

embedding_dim: 64
num_layers: 4

epochs: 1000
batch_size: 2048
optimizer: adam
lr: 1.e-3
weight_decay: 1.e-4

monitors: [LOSS, Recall@1, Recall@10, Recall@20, NDCG@10, NDCG@20]
which4best: NDCG@20