dataset: Diginetica_2507_Chron
root: ../../data
epochs: 30
batch_size: 512
lr: 1.e-3
weight_decay: 1.e-8
embedding_dim: 100
hidden_size: 100
emb_dropout_rate: 0.4
ct_dropout_rate: 0.3
num_gru_layers: 1