dataset: Frappe_x1_BARS
root: ../../data

embedding_dim: 4
num_layers: 3
hidden_dims: 64,32
hidden_dropout_rate: 0.

epochs: 1
batch_size: 128
optimizer: adam
lr: 1.e-3
weight_decay: 1.e-8

monitors: [LOSS, LOGLOSS, AUC, GAUC]
which4best: AUC