root: ../../data
dataset: AmazonBeauty_550_Chron
maxlen: 50
num_heads: 1
num_blocks: 2
hidden_size: 64
dropout_rate: 0.5
epochs: 200
batch_size: 512
optimizer: adam
beta1: 0.9
beta2: 0.98
lr: 1.e-3
weight_decay: 0.