root: ../../data
dataset: MovieLens1M_550_Chron
maxlen: 200
num_heads: 1
num_blocks: 2
hidden_size: 64
dropout_rate: 0.2
epochs: 200
batch_size: 128
optimizer: adam
beta1: 0.9
beta2: 0.98
lr: 1.e-3
weight_decay: 0.